import pandas as pd
sFileName='Good-or-Bad.csv'
print('Loading :',sFileName)
RawData=pd.read_csv(sFileName,header=0)
print('## Raw Data Values')
print(RawData)
print('## Data Profile')
print('Rows :',RawData.shape[0])
print('Columns :',RawData.shape[1])
TestData=RawData.dropna(axis=1, how='all')
print(TestData)
print('Rows :',TestData.shape[0])
print('Columns :',TestData.shape[1])
TestData.to_csv('Good-or-Bad-01.csv', index = False)
TestData=RawData.dropna(axis=1, how='any')
print('Rows :',TestData.shape[0])
print('Columns :',TestData.shape[1])
TestData.to_csv('Good-or-Bad-02.csv', index = False)
TestData=RawData.dropna(thresh=2)
print('Rows :',TestData.shape[0])
print('Columns :',TestData.shape[1])
TestData.to_csv('Good-or-Bad-03.csv', index = False)
print('### Done!! #####################')
